name: E2E tests

on:
  push:
    branches: ["**"]
  pull_request:
  workflow_dispatch:

concurrency:
  group: e2e-${{ github.ref }}
  cancel-in-progress: true

jobs:
  e2e:
    runs-on: ubuntu-latest
    timeout-minutes: 60
    permissions:
      contents: read
    defaults:
      run:
        working-directory: tests/e2e

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm
          cache-dependency-path: tests/e2e/package-lock.json

      - name: Cache Cypress binary
        uses: actions/cache@v4
        with:
          path: ~/.cache/Cypress
          key: cypress-${{ runner.os }}-${{ hashFiles('tests/e2e/package-lock.json') }}
          restore-keys: |
            cypress-${{ runner.os }}-

      - name: Install NPM dependencies
        run: npm ci

      - name: Start application stack
        run: npm run start

      - name: Run E2E tests (Cypress)
        env:
          CI: true
        run: npm run tests

      - name: Upload Cypress videos
        if: failure() || success()
        uses: actions/upload-artifact@v4
        with:
          name: cypress-videos
          if-no-files-found: ignore
          path: |
            tests/e2e/tests/cypress/videos/**
            tests/e2e/cypress/videos/**

      - name: Upload Cypress screenshots
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: cypress-screenshots
          if-no-files-found: ignore
          path: |
            tests/e2e/tests/cypress/screenshots/**
            tests/e2e/cypress/screenshots/**